# Railway.toml
[build]
  # Este comando se ejecutar치 para construir tu aplicaci칩n
  command = "pip install -r requirements.txt"

[dev]
  # Este comando se ejecutar치 para iniciar tu aplicaci칩n
  command = "gunicorn muebles_backend.wsgi:application --bind 0.0.0.0:8000"
